name: Check for compose manager updates

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: bundles  # Checkout the 'bundles' branch

      - name: Install Python dependencies
        run: |
          sudo apt-get install jq -y
          python -m pip install requests

      - name: Get artifact URL
        id: get_artifact
        run: |
          WORKFLOW_RUNS=$(curl -sS -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success")
          if [ -z "$WORKFLOW_RUNS" ]; then
            echo "Failed to fetch workflow runs."
            exit 1
          fi

          ARTIFACT_URL=$(jq -r '.workflow_runs[0].artifacts_url // empty' <<<"$WORKFLOW_RUNS")
          if [ -z "$ARTIFACT_URL" ]; then
            echo "Failed to fetch artifact URL."
            exit 1
          fi

          ARTIFACTS=$(curl -sS -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" "$ARTIFACT_URL")
          if [ -z "$ARTIFACTS" ]; then
            echo "Failed to fetch artifacts."
            exit 1
          fi

          RUN_ID=$(jq -r '.workflow_runs[0].id' <<<"$WORKFLOW_RUNS")
          ARTIFACT_ID=$(jq -r '.artifacts[]? | select(.name == "revanced-manager") | .id' <<<"$ARTIFACTS" | head -n 1)
          if [ -z "$ARTIFACT_ID" ]; then
            echo "Failed to fetch artifact ID."
            exit 1
          fi

          ARTIFACT_DOWNLOAD_URL="https://github.com/ReVanced/revanced-manager/actions/runs/${RUN_ID}/artifacts/${ARTIFACT_ID}"
          echo "artifact_url=$ARTIFACT_DOWNLOAD_URL" >> "$GITHUB_OUTPUT"
          echo "ARTIFACT_DOWNLOAD_URL: $ARTIFACT_DOWNLOAD_URL"
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Check if README needs update
        id: check_readme
        run: |
          python check_readme.py ${{ steps.get_artifact.outputs.artifact_url }}
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          TARGET_BRANCH: bundles

      - name: Update README
        if: steps.check_readme.outputs.needs_update == 'true'
        run: |
          python update_readme.py ${{ steps.get_artifact.outputs.artifact_url }}
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          TARGET_BRANCH: bundles

      - name: Send Discord Notification
        if: steps.check_readme.outputs.needs_update == 'true'
        uses: tsickert/discord-webhook@master
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: '||@everyone||'
          embed-title: 'ReVanced Manager Compose Update'
          embed-description: |
            The manager download link has been updated by the [Manager Update Checker Workflow](https://github.com/Jman-Github/ReVanced-Patch-Bundles/actions/workflows/manager-update-checker.yml).

            [Latest Download](${{ steps.get_artifact.outputs.artifact_url }})
          embed-color: '65280'
          embed-author-name: 'Manager Update Checker Workflow'
          embed-author-icon-url: 'https://github.gallerycdn.vsassets.io/extensions/github/vscode-github-actions/0.26.2/1694016984133/Microsoft.VisualStudio.Services.Icons.Default'
          embed-thumbnail-url: 'https://cdn-icons-png.flaticon.com/512/5278/5278658.png'
          username: 'ReVanced-Patch-Bundles'
          avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'
