name: Patch bundle updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_for_updates:
    name: Check for bundle updates
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests httpx black
        working-directory: ${{ github.workspace }}

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Run generate_bundles.py
        id: run_generate_bundles
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install requests httpx
          python generate_bundles.py
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Grant execute permission
        run: chmod +x ./bundle-parser/gradlew

      - name: Generate patches list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./bundle-parser/gradlew --project-dir bundle-parser run

      - name: Generate patch list catalog
        run: |
          python generate_patch_list_catalog.py
          black generate_patch_list_catalog.py

      - name: Commit new files
        run: |
          git add '*.json' patch-bundles/PATCH-LIST-CATALOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit. Exiting..."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            git commit -m 'feat: `patch-bundles` update'
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Find commit for changed files
        id: find_commit
        if: env.has_changes == 'true'
        run: |
          changed_files=$(git diff --name-only HEAD^ -- '*.json')
          if [ -z "$changed_files" ]; then
            echo "changed_files=" >> $GITHUB_ENV
          else
            echo "$changed_files" > changed_files.txt
            echo "changed_files=changed_files.txt" >> $GITHUB_ENV
          fi

      - name: Build summary of updated bundles
        if: env.has_changes == 'true' && env.changed_files != ''
        run: |
          python build_summary.py

      - name: Push changes
        if: env.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bundles

      - name: Create artifact of changed files
        if: env.has_changes == 'true' && env.changed_files != ''
        uses: actions/upload-artifact@main
        with:
          name: changed_files
          path: changed_files.txt

      - name: Create artifact of updated bundles
        if: env.has_changes == 'true' && env.changed_files != ''
        uses: actions/upload-artifact@main
        with:
          name: updated_bundles
          path: updated-bundles.txt
